//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoDiscos.Properties
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_discos
    {
        public int IdDisco { get; set; }
        public string Titulo { get; set; }
        public Nullable<double> Agno { get; set; }
        public Nullable<int> idInterprete { get; set; }
        public string NombreInterp { get; set; }
        public Nullable<int> Puntuacion { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string tipoDisco { get; set; }
        public int IdCliente { get; set; }
        public string NombreCliente { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
    }
}
